CREATE DATABASE data_makanan;

CREATE TABLE `makanan`(
	`id` int NOT NULL AUTO_INCREMENT,
    `nama` varchar(255) NOT NULL,
    `harga` float NOT NULL,
    `rating` float NOT NULL,
	`jarak` float NOT NULL ,
	`lokasi` varchar(255) NOT NULL,
	PRIMARY KEY (`id`)
);

INSERT INTO makanan (Nama, Harga, Rating, Jarak, Lokasi) VALUES
('Ayam Gepuk Pak Gembus', 24, 4.4, 1.2, 'https://maps.app.goo.gl/5Ss9Ry4gCaM1GV7z6'),
('Mie Ayam "Baso Budi"', 14, 4.8, 1, 'https://maps.app.goo.gl/BtxLJo47FzSzrCmL9'),
('Batagor MSU', 10, 5, 1.3, 'https://maps.app.goo.gl/Sx9945WJkQXs24UP7'),
('Sate Suramadu', 25, 4.3, 1.3, 'https://maps.app.goo.gl/skXXHUmvV1WVZVXx8'),
('Ketoprak Mas No', 15, 4.9, 0.8, 'https://maps.app.goo.gl/GMP4A8dHAc9pS9CL6'),
('Nasi Pecel Lele "Lumintu 768"', 15, 4.5, 1, 'https://maps.app.goo.gl/DXgV4WZjcoSELyaAA'),
('Geprek Crispy "Ayam Crisbar"', 14, 4.4, 1.1, 'https://maps.app.goo.gl/FcjSGXRb5xTKavMf6'),
('Mie Baso "Mas Japra Solo"', 15, 4.7, 1.2, 'https://maps.app.goo.gl/nHSgDhB6JcXZHTVT8'),
('Mie Ayam "Jabrig"', 10, 4.5, 1.2, 'https://maps.app.goo.gl/t9giWhD6E3MdT7o78'),
('Yakiniku Rice Bowl "Spicy Yakiniku"', 20, 4.8, 0.95, 'https://maps.app.goo.gl/EgWp5aQSPKZvhNPS7'),
('Classic Beef Kebab "Merhaba Kebab"', 18, 5, 1.4, 'https://maps.app.goo.gl/fpLQPxgiSeJDwdjx8'),
('Paket Jumbo Chicken "Chicken William"', 15, 4.3, 1.7, 'https://maps.app.goo.gl/drA7Kznw118A6uiG6'),
('Paket Nila Merah Nasi "Ikan Dan Ayam Bakar Pesona Bali"', 26, 5, 3.1, 'https://maps.app.goo.gl/BHxZu27AUfJAmxum7'),
('Seblak "Azka"', 15, 4, 1, 'https://maps.app.goo.gl/3ithL5ePS8kyPU4NA'),
('Nasi Goreng Telor "Kedai Aas"', 12, 4.6, 1.4, 'https://maps.app.goo.gl/2Lh7thn32hUgzbR69'),
('Kwetiau Goreng Seafood "Kedai Aas"', 14, 4.6, 1.4, 'https://maps.app.goo.gl/2Lh7thn32hUgzbR69'),
('Nasi Goreng "Moro Tresno"', 13, 2.3, 0.9, 'https://maps.app.goo.gl/4gkAkb4WL5AN5WAt6'),
('Mie Tek-Tek "Warkop Djoeang"', 10, 3, 1.1, 'https://maps.app.goo.gl/RfnkhfRrsA6qjum49'),
('Dori Fish "Mr. Mangkok"', 18, 4.5, 1.8, 'https://maps.app.goo.gl/hPWTHf8jFhcSNnK66'),
('Capcay Ayam "Kedai Aas"', 13, 4.6, 1.4, 'https://maps.app.goo.gl/2Lh7thn32hUgzbR69'),
('Nasi Bakar Ayam Nasi Bakar Dapoer Koering', 16, 5, 1.1, 'https://maps.app.goo.gl/xqBhbfdYghr3Ukzt5'),
('Nasi Bakar Cumi Nasi Bakar Dapoer Koering', 17, 5, 1.1, 'https://maps.app.goo.gl/xqBhbfdYghr3Ukzt5'),
('Soto Betawi Daging Soto Betawi Pak Odang', 20, 4.7, 1.2, 'https://maps.app.goo.gl/4YVTsCYyfR9gwXy67'),
('Soto Betawi Ayam Soto Betawi Pak Odang', 15, 4.7, 1.2, 'https://maps.app.goo.gl/4YVTsCYyfR9gwXy67'),
('Mie Baek Asin / Manis', 12, 4.8, 1.3, 'https://maps.app.goo.gl/yff8xUZwVR9QBsJs9'),
('Nasi Chicken Teriyaki WS Hotplate', 16, 4.5, 1.1, 'https://maps.app.goo.gl/jHK47AawhdgoshrUA'),
('Mie Bakso Cincang Sedang Bakso Joko Tingkir', 14, 3.8, 1.3, 'https://maps.app.goo.gl/tNhZectsrekuQzL79'),
('Mie Bakso Cincang Jumbo Bakso Joko Tingkir', 18, 3.8, 1.3, 'https://maps.app.goo.gl/tNhZectsrekuQzL79'),
('Nasi Ayam Bistik Waroeng Steak 77', 20, 5, 0.95, 'https://maps.app.goo.gl/hhYPM9cWkt5vJUKL9'),
('Steak Ayam Waroeng Steak 77', 25, 5, 0.95, 'https://maps.app.goo.gl/hhYPM9cWkt5vJUKL9'),
('Sambal Bakar Kedai Beringas', 17, 4.7, 1.3, 'https://maps.app.goo.gl/3RP8JzE12XCZdBn77'),
('Warung Munjul', 18, 4.6, 1, 'https://maps.app.goo.gl/k9AjpKJXMKQt33mTA'),
('Ayam Geprek Meriam', 19, 4.8, 1.2, 'https://maps.app.goo.gl/8UrEWYqfQxVN7DKAA'),
('Warkop Bang Zek', 10, 4.9, 1.6, 'https://maps.app.goo.gl/GNm8tVcTBKCTtTZd8'),
('Ketoprak Khas Cirebon Berkah 2', 13, 4.7, 1.6, 'https://maps.app.goo.gl/tiDq6MJxNzWJ4U256'),
('Sate Avanger', 25, 4.4, 2.1, 'https://maps.app.goo.gl/bxbZPG9T1Y5N4EP16'),
('Bihun Goreng/Rebus Moro Tresno', 13, 2.3, 0.9, 'https://maps.app.goo.gl/4gkAkb4WL5AN5WAt6'),
('Nasi Goreng Groei Coffe', 22, 4.1, 0.9, 'https://maps.app.goo.gl/Eo6ZaF6G5np1mScp8'),
('Nasi Katsu Chicken KatsuNa', 18, 4.8, 1, 'https://maps.app.goo.gl/4VqJMi6CNyuaZhpZ7'),
('Ramen PiKatsu & Ramen', 25, 4, 1.3, 'https://maps.app.goo.gl/TPSXRzRnGavJJrzN8'),
('Nasi Katsu Original PiKatsu & Ramen', 15, 4, 1.3, 'https://maps.app.goo.gl/TPSXRzRnGavJJrzN8'),
('Nasi Telur Bento Kopi', 15, 4.5, 1.9, 'https://maps.app.goo.gl/4h882a3AYyFihZ2H7'),
('Nasi Ayam Mulya Rasa Kantin & Catering', 15, 4.7, 1.2, 'https://maps.app.goo.gl/4JJwUiZDG2F9aY5C9'),
('Ayam Gepuk Nuklir', 18, 4.4, 1, 'https://maps.app.goo.gl/N486Eu2QM7ZmqGXW7'),
('Nasi Kuning Nasi Uduk Ibu Suryati', 12, 5, 1.6, 'https://maps.app.goo.gl/QNnxfWhNCKSSJ4jo6'),
('Nasi Kebuli Ayam Kebuli Baim', 30, 4.1, 1.3, 'https://maps.app.goo.gl/a4iAp7ynz6tAHQkU9'),
('Paket Ayam Paha Bebeke Om Aris', 23, 4.7, 1.2, 'https://maps.app.goo.gl/JApkhHJDpijuQACp7'),
('Paket Bebek Paha Bebeke Om Aris', 33, 4.7, 1.2, 'https://maps.app.goo.gl/JApkhHJDpijuQACp7'),
('Mie Baso Amin', 13, 4.4, 1.2, 'https://maps.app.goo.gl/RfDp7eqPLZpmdRAC7'),
('Bubur Ayam Cianjur', 11, 4.8, 1.2, 'https://maps.app.goo.gl/QAXUQPrii76jyCxU6');
